{% set name = "fuzzytm" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/FuzzyTM-{{ version }}.tar.gz
  sha256: 2042e48dddffc9cda5058b0b3fa9a6b3d2c471739f56d34da2810a08c7fd06d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - pyfume
    - gensim

test:
  imports:
    - FuzzyTM
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ERijck/FuzzyTM
  summary: A Python package for Fuzzy Topic Models
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
